http {
  server {
      listen 8080;
      
      client_max_body_size 10485760;

      error_page 404 /errors/404.html;

      root ./docs/html;

      index empty.html;

      location / {
          limit_except GET;
          autoindex off;
          index empty.html;
      }
  }
}
