http {
    server {
        listen 8080;

        root ./docs/html;

        error_page 400 /errors/400.html;
        error_page 403 /errors/403.html;
        error_page 404 /errors/404.html;
        error_page 405 /errors/405.html;
        error_page 500 /errors/500.html;
        error_page 502 /errors/502.html;
        error_page 504 /errors/504.html;

        location / {
            limit_except GET;
            autoindex on;
            index empty.html;
            cgi_pass .bla ./cgi-bin/cgi_tester;
            cgi_enable on;
        }

        location /post_body {
            limit_except POST;
            client_max_body_size 100;
        }

        location /directory {
            limit_except GET POST;
            root ./YoupiBanane;
            autoindex off;
            index youpi.bad_extension;
            cgi_pass .bla /home/smoore-a/git/webserv/cgi-bin/cgi_tester;
            cgi_enable on;
            client_max_body_size 200000000;
        }
    }
}
