server {
    listen 8080;
    server_name localhost;
    root ./www/website;
    index index.html;

    location / {
        allow_methods GET;
        autoindex on;
    }

    error_page 404 /docs/html/errors/404.html;
}
